ClientServer/Controllers/FridgeProductsController.cs
using AutoMapper;
using Contracts;
using Entities.Models;
using Entities.RequestFeatures;
using Entities.Requests.FridgeProducts;
using Entities.Responses.Account;
using Entities.Responses.FridgeProducts;
using Entities.ViewModels.FridgeProducts;
using Entities.ViewModels.Products;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NLog;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ClientServer.Controllers
{
    [Route("Fridges/{fridgeId}/Products")]
    public class FridgeProductsController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILoggerManager _logger;
        private readonly IMessenger _messenger;

        public FridgeProductsController(IMapper mapper, ILoggerManager logger, IMessenger messenger)
        {
            _mapper = mapper;
            _logger = logger;
            _messenger = messenger;
        }

        [HttpGet]
        public async Task<IActionResult> Products(Guid fridgeId, [FromQuery] int pageNumber = 1)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");

            string token = HttpContext.Request.Cookies["JWT"];
            string query = $"pageNumber={pageNumber}&pageSize={5}";

            var jsonResponse = await _messenger.GetRequestAsync($"https://localhost:44381/api/fridges/{fridgeId}/products", token, query);
            switch (jsonResponse.StatusCode)
            {
                case 200:
                    {
                        var fridgeProductsResponse = JsonConvert.DeserializeObject<IEnumerable<FridgeProductResponse>>(jsonResponse.Message);
                        var fridgeProducts = _mapper.Map<IEnumerable<FridgeProduct>>(fridgeProductsResponse);
                        var fridgeProductsViewModel = new FridgeProductsViewModel()
                        {
                            fridgeProducts = _mapper.Map<IEnumerable<FridgeProductViewModel>>(fridgeProducts),
                            MetaData = JsonConvert.DeserializeObject<MetaData>(jsonResponse.Headres["X-Pagination"]),
                            FridgeId = fridgeId
                        };
                        return View(fridgeProductsViewModel);
                    }
                case 401:
                    {
                        return RedirectToAction("Login", "Account");
                    }
                case 404:
                    {
                        return RedirectToAction("Fridges", "Fridges");
                    }
                default:
                    {
                        return RedirectToAction("Fridge", "Fridges", new { id = fridgeId });
                    }
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid fridgeId, Guid id)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");
            if (id == Guid.Empty)
                return RedirectToAction("Products", new { fridgeId = fridgeId });

            string token = HttpContext.Request.Cookies["JWT"];

            var jsonResponse = await _messenger.DeleteRequestAsync($"https://localhost:44381/api/fridges/{fridgeId}/products/{id}", token);

            switch (jsonResponse.StatusCode)
            {
                case 401:
                    {
                        return RedirectToAction("Login", "Account");
                    }
                case 404:
                    {
                        return RedirectToAction("Fridge", "Fridges", new { id = fridgeId });
                    }
                default:
                    {
                        return RedirectToAction("Products", new { fridgeId = fridgeId });
                    }
            }
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> Product(Guid fridgeId, Guid id)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");
            if (id == Guid.Empty)
                return RedirectToAction("Products", new { fridgeId = fridgeId });

            string token = HttpContext.Request.Cookies["JWT"];

            var jsonResponse = await _messenger.GetRequestAsync($"https://localhost:44381/api/fridges/{fridgeId}/products/{id}", token, null);
            switch (jsonResponse.StatusCode)
            {
                case 200:
                    {
                        var fridgeProductResponse = JsonConvert.DeserializeObject<FridgeProductResponse>(jsonResponse.Message);
                        var fridgeProduct = _mapper.Map<FridgeProduct>(fridgeProductResponse);
                        var fridgeProductViewModel = _mapper.Map<FridgeProductViewModel>(fridgeProduct);
                        fridgeProductViewModel.FridgeId = fridgeId;
                        return View(fridgeProductViewModel);
                    }
                case 401:
                    {
                        return RedirectToAction("Login", "Account");
                    }
                case 404:
                    {
                        return RedirectToAction("Fridge", "Fridges", new { id = fridgeId });
                    }
                default:
                    {
                        return RedirectToAction("Products", new { fridgeId = fridgeId });
                    }
            }
        }

        [HttpGet("Update")]
        public async Task<IActionResult> Update(Guid fridgeId, [FromQuery] Guid id)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");
            if (id == Guid.Empty)
                return RedirectToAction("Products", new { fridgeId = fridgeId });

            string token = HttpContext.Request.Cookies["JWT"];

            var jsonResponse = await _messenger.GetRequestAsync($"https://localhost:44381/api/fridges/{fridgeId}/products/{id}", token, null);
            switch (jsonResponse.StatusCode)
            {
                case 200:
                    {
                        var fridgeProductResponse = JsonConvert.DeserializeObject<FridgeProductResponse>(jsonResponse.Message);
                        var fridgeProduct = _mapper.Map<FridgeProduct>(fridgeProductResponse);
                        var updateFridgeProductViewModel = _mapper.Map<UpdateFridgeProductViewModel>(fridgeProduct);
                        updateFridgeProductViewModel.FridgeId = fridgeId;
                        return View(updateFridgeProductViewModel);
                    }
                case 401:
                    {
                        return RedirectToAction("Login", "Account");
                    }
                case 404:
                    {
                        return RedirectToAction("Fridge", "Fridges", new { id = fridgeId });
                    }
                default:
                    {
                        return RedirectToAction("Products", new { fridgeId = fridgeId });
                    }
            }
        }

        [HttpPost("Update")]
        public async Task<IActionResult> Update(Guid fridgeId, UpdateFridgeProductViewModel model)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");

            if (ModelState.IsValid)
            {
                var fridgeProduct = _mapper.Map<FridgeProduct>(model);
                var fridgeProductRequest = _mapper.Map<UpdateFridgeProductRequest>(fridgeProduct);

                string token = HttpContext.Request.Cookies["JWT"];
                _logger.LogInfo(fridgeProduct.ProductId.ToString());
                string jsonRequest = JsonConvert.SerializeObject(fridgeProductRequest);
                var jsonResponse = await _messenger.PutRequestAsync($"https://localhost:44381/api/fridges/{fridgeId}/products/{fridgeProduct.ProductId}", token, jsonRequest);
                _logger.LogInfo(jsonResponse.StatusCode.ToString());
                switch (jsonResponse.StatusCode)
                {
                    case 204:
                        {
                            return RedirectToAction("Product", new { fridgeId = fridgeId, id = fridgeProduct.ProductId });
                        }
                    case 404:
                        {
                            return RedirectToAction("Fridge", "Fridges", new { id = fridgeId });
                        }
                    case int code when (code == 400 || code == 422):
                        {
                            var fridgeProductResponse = new UpdateFridgeProductResponse()
                            {
                                Errors = JsonConvert.DeserializeObject<Dictionary<string, IEnumerable<string>>>(jsonResponse.Message)
                            };
                            foreach (var error in fridgeProductResponse.Errors)
                                foreach (var message in error.Value)
                                    ModelState.AddModelError("", message);
                        }
                        break;
                    case 401:
                        {
                            return RedirectToAction("Login", "Account");
                        }
                    default:
                        {
                            return RedirectToAction("Products", new { fridgeId = fridgeId });
                        }

                }
            }
            model.FridgeId = fridgeId;
            return View(model);
        }

        [HttpGet("Create/Products")]
        public async Task<IActionResult> AllProducts(Guid fridgeId, [FromQuery] int pageNumber = 1)
        {
            if (fridgeId == Guid.Empty)
                return RedirectToAction("Fridges", "Fridges");
            string token = HttpContext.Request.Cookies["JWT"];
            string query = $"pageNumber={pageNumber}&pageSize={5}";

ClientServer/Views/Fridges/Create.cshtml
@using Entities.ViewModels.Fridges
@model CreateFridgeViewModel
 @{
    ViewData["Title"] = "Create fridge";
 }

 <h1>New fridge</h1>
<a asp-action="Models" style="margin-right:100%" 
     class="btn btn-primary">
     Models  
</a>
<form method="post" asp-action="Create" asp-route-modelId="@Model.ModelId">
    <div asp-validation-summary="ModelOnly" id="myCustomSummary" class="text-danger" style="margin:auto"></div>
    <div class="form-group">
        <label asp-for="Name">Fridge name</label><br />
        <input asp-for="Name" style='width:300px;margin:auto' class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="OwnerName">Owner name</label><br />
        <input asp-for="OwnerName" style='width:300px;margin:auto' class="form-control"/>
        <span asp-validation-for="OwnerName" class="text-danger"></span>
    </div>
    <div style="margin-top:15px">
        <button type="submit" class="btn btn-success">Create</button>
    </div>
</form>

ClientServer/Views/Fridges/Fridge.cshtml
@using Entities.ViewModels.Fridges
@model FridgeViewModel
 @{
    ViewData["Title"] = "Fridge";
 }
 <h1>Fridge</h1>
<a asp-action="Fridges" style="margin-right:100%" 
     class="btn btn-primary">
     Fridges  
</a>
<div style="color:#007bff">
    <h3>
        <span style="color:black">
            Fridge name:
        </span> 
            @Model.Name
    </h3>
    <h3>
        <span style="color:black">
            Owner name:
        </span> 
            @Model.OwnerName
    </h3>
    <h3>
        <span style="color:black">
            Model name:
        </span> 
            @Model.Model.Name
    </h3>
    <h3>
        <span style="color:black">
            Year:
        </span> 
            @Model.Model.Year
    </h3>
</div>
<div style="margin-top:15px">
    <a asp-controller="FridgeProducts" asp-action="Products" asp-route-fridgeId="@Model.Id" 
         class="btn btn-sm btn-info">
         Products  
    </a>
    <a asp-action="Update" asp-route-id="@Model.Id" 
         class="btn btn-sm btn-primary" style="margin-left:25px">
         Change  
    </a>
</div>

ClientServer/Views/Fridges/Fridges.cshtml
@using Entities.ViewModels.Fridges
@model FridgesViewModel
 @{
    ViewData["Title"] = "Fridges";
 }
<h1>List of fridges</h1>
<a asp-action="Models" style="margin-right:100%" 
     class="btn btn-primary">
     Create  
</a>
<table class="table">
    @foreach (var fridge in Model.Fridges)
    {
        <tr>
            <td>@fridge.Name</td>
            <td>
                <a asp-action="Fridge" 
                    asp-route-id="@fridge.Id"
                    class="btn btn-sm btn-info">
                        Info
                </a>
            </td>
            <td>
                <button type="button" class="btn btn-danger" value="@fridge.Id" 
                data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="setId(this)">
                    Delete
                </button> 
            </td>        
        </tr>
    }
</table>
<div style="margin-top:15px">
    @if(Model.MetaData.HasPrevious)
    {
        <a asp-action="Fridges"
            asp-route-pageNumber="@(Model.MetaData.CurrentPage-1)"
            class="btn btn-sm btn-outline-primary">
                <i class="arrow left"></i>Back
        </a>
    }
    @if(Model.MetaData.HasNext)
    {
        <a asp-action="Fridges"
            asp-route-pageNumber="@(Model.MetaData.CurrentPage+1)"
            class="btn btn-sm btn-outline-primary">
                Next<i class="arrow right"></i>
        </a>
    }
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <h3>Are you sure?</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <form asp-action="Delete" method="post">
            <input type="hidden" id="id" name="id"/>
            <button type="submit" class="btn btn-danger">
                Yes
            </button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
    function setId(button)
    {
        document.getElementById("id").value=button.value;
    }
</script>

ClientServer/Views/Fridges/Models.cshtml
@using Entities.ViewModels.FridgeModels
@model FridgeModelsViewModel
 @{
    ViewData["Title"] = "Fridge models";
 }
<h1>Choose model for new fridge</h1>
<a asp-action="Fridges" style="margin-right:100%" 
     class="btn btn-primary">
     Fridges  
</a>
<table class="table">
    @foreach (var fridgeModel in Model.FridgeModels)
    {
        <tr>
            <td>
                <a asp-action="Create" 
                 asp-route-modelId="@fridgeModel.Id"
                 class="btn btn-sm btn-outline-primary">
                 @fridgeModel.Name
                </a>
            </td>
        </tr>
    }
</table>
<div style="margin-top:15px">
    @if(Model.MetaData.HasPrevious)
    {
        <a asp-action="Models"
            asp-route-pageNumber="@(Model.MetaData.CurrentPage-1)"
            class="btn btn-sm btn-outline-primary">
                <i class="arrow left"></i>Back
        </a>
    }
    @if(Model.MetaData.HasNext)
    {
        <a asp-action="Models"
            asp-route-pageNumber="@(Model.MetaData.CurrentPage+1)"
            class="btn btn-sm btn-outline-primary">
                Next<i class="arrow right"></i>
        </a>
    }
</div>

ClientServer/Views/Fridges/Update.cshtml
@using Entities.ViewModels.Fridges
@model UpdateFridgeViewModel
 @{
    ViewData["Title"] = "Update fridge";
 }
 <h1>Update fridge</h1>
<a asp-action="Fridge" asp-route-id="@Model.Id" style="margin-right:100%" 
     class="btn btn-primary">
     Back  
</a>
<form method="post" asp-action="Update">
    <div asp-validation-summary="ModelOnly" id="myCustomSummary" class="text-danger" style="margin:auto"></div>
    <div class="form-group">
        <label asp-for="Name">Fridge name</label><br />
        <input asp-for="Name" value="@Model.Name"
         style='width:300px;margin:auto' class="form-control"/>
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="OwnerName">Owner name</label><br />
        <input asp-for="OwnerName" value="@Model.OwnerName"
         style='width:300px;margin:auto' class="form-control"/>
        <span asp-validation-for="OwnerName" class="text-danger"></span>
    </div>
    <input type="hidden" name="Id" value="@Model.Id"/>
    <div style="margin-top:15px">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>